export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  SERVICE_NOT_ALLOWED: "SERVICE_NOT_ALLOWED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  PHONE_ALREADY_USED: "PHONE_ALREADY_USED",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
